### ISSUE TITLE
There are some API not returning JSON and thrown exception by the library

### ISSUE THREAD

**Issue by eslym** [GeoffSelby/nevexo-forge-javascript-sdk#27]
for example [get deployment script](https://forge.laravel.com/api-documentation#get-deployment-script) is returning the shell script directly instead of `json` but this library always assume the result is `json`.

the [obtain letsencrypt certificate](https://forge.laravel.com/api-documentation#obtain-a-letsencrypt-certificate) endpoint also have similar problem

**Comment by GeoffSelby** [comment]
I must have missed the note in the api docs about the response being a string for the get deployment script endpoint.

The obtain a letsencrypt endpoint doesn't mention the type of response but I assume it's a string as well? I don't have access to a forge account anymore so I can't be sure, I just rely on docs. 

If you can share a sample response from the api itself for both, I'll get a fix shipped tonight.

Thanks for bringing this to my attention.

**Comment by eslym** [comment]
> I must have missed the note in the api docs about the response being a string for the get deployment script endpoint.
> 
> The obtain a letsencrypt endpoint doesn't mention the type of response but I assume it's a string as well? I don't have access to a forge account anymore so I can't be sure, I just rely on docs.
> 
> If you can share a sample response from the api itself for both, I'll get a fix shipped tonight.
> 
> Thanks for bringing this to my attention.

oh sorry, the one having response type issue is not obtain certificate, is actually [activate certificate](https://forge.laravel.com/api-documentation#activate-certificate), which return nothing at all

p/s: configuration files API also returning text instead of json

**Comment by GeoffSelby** [comment]
I just shipped a patch that should fix this. Update to 1.2.1. If you come across any other problems with a response, let me know.
